---

- hosts: railsapp
  remote_user: vagrant
  sudo: yes
  vars:
    deploy_user: deploy
    release_path: /home/{{ deploy_user }}/railsfuza
    rails_env: production
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes cache_valid_time=86400

    - name: start nginx
      service: name=nginx state=started

    - name: add brightbox ruby repository
      apt_repository:
        repo: ppa:brightbox/ruby-ng
        state: present

    - name: install ruby
      apt:
        name: "{{ item }}"
      with_items:
        - ruby2.1
        - ruby2.1-dev
        - ruby-switch

    - name: install bundler gem
      gem:
        name: bundler
        state: present
        user_install: no

    - name: add account group
      group:
        name: "{{ deploy_user }}"

    - name: add account user
      user:
        name: "{{ deploy_user }}"
        group: "{{ deploy_user }}"

    - name: install essential build/dev tools and compilers
      apt: name={{ item }}
      with_items:
        - build-essential
        - automake
        - autoconf
        - g++
        - git
        - libssl-dev
        - libtool
        - python-httplib2
        - ntp
        - sqlite3
        - libsqlite3-dev

    - name: fetch source code from git
      sudo_user: "{{ deploy_user }}"
      git:
        repo: https://github.com/stevenringo/railsfuza.git
        dest: "{{ release_path }}"
        version: master
      tags: deploy

    - name: bundle install
      sudo_user: "{{ deploy_user }}"
      command: bundle install --deployment chdir={{ release_path }}
      environment:
        RAILS_ENV: "{{ rails_env }}"
      tags: deploy

    - name: "rake db:migrate"
      sudo_user: "{{ deploy_user }}"
      command: bundle exec rake db:migrate chdir={{ release_path }}
      environment:
        RAILS_ENV: production
      tags: deploy
