---

- hosts: railsapp
  remote_user: vagrant
  tasks:
    - name: install nginx
      apt: name=nginx state=present update_cache=yes cache_valid_time=3600
      sudo: yes

    - name: start nginx
      service: name=nginx state=started
      sudo: yes
