---

- hosts: railsapp
  remote_user: vagrant
  sudo: yes
  vars:
    deploy_user: deploy
    release_path: /home/{{ deploy_user }}/railsfuza
    rails_env: production
    db_username: railsfuza
    db_password: i_@m_a_s3kr1t

  roles:
    - { role: account, account_user: "{{ deploy_user }}" }
    - nginx

  tasks:

    - name: add brightbox ruby repository
      apt_repository:
        repo: ppa:brightbox/ruby-ng
        state: present

    - name: install ruby
      apt:
        name: "{{ item }}"
      with_items:
        - ruby2.1
        - ruby2.1-dev
        - ruby-switch

    - name: install bundler gem
      gem:
        name: bundler
        state: present
        user_install: no

    - name: add nodejs apt repository
      apt_repository: repo='deb https://deb.nodesource.com/node precise main'

    - name: add nodejs signing key
      apt_key: url='https://deb.nodesource.com/gpgkey/nodesource.gpg.key'

    - name: install nodejs
      apt: name=nodejs state=present update_cache=yes

    - name: install essential build/dev tools and compilers
      apt: name={{ item }}
      with_items:
        - build-essential
        - automake
        - autoconf
        - g++
        - git
        - libssl-dev
        - libtool
        - python-httplib2
        - ntp
        - sqlite3
        - libsqlite3-dev

    - name: fetch source code from git
      sudo_user: "{{ deploy_user }}"
      git:
        repo: https://github.com/stevenringo/railsfuza.git
        dest: "{{ release_path }}"
        version: master
      tags: deploy

    - name: copy database.yml
      sudo_user: "{{ deploy_user }}"
      template:
        src: templates/database.yml.j2
        dest: "{{ release_path }}/config/database.yml"
        mode: 0644
      tags: deploy

    - name: bundle install
      sudo_user: "{{ deploy_user }}"
      command: bundle install --deployment chdir={{ release_path }}
      environment:
        RAILS_ENV: "{{ rails_env }}"
      tags: deploy

    - name: "rake db:migrate"
      sudo_user: "{{ deploy_user }}"
      command: bundle exec rake db:migrate chdir={{ release_path }}
      environment:
        RAILS_ENV: "{{ rails_env }}"
      tags: deploy

    - name: compile js/css assets
      sudo_user: "{{ deploy_user }}"
      command: bundle exec rake assets:precompile chdir={{ release_path }}
      environment:
        RAILS_ENV: "{{ rails_env }}"
      tags: deploy

    - name: write unicorn init file
      template: src=templates/unicorn.init.j2 dest=/etc/init.d/railsfuza owner={{ deploy_user }} group={{ deploy_user }} mode=0755
      notify: restart unicorn
      tags: deploy

    - name: write unicorn config file
      template: src=templates/unicorn.rb.j2 dest={{ release_path }}/config/unicorn.rb owner={{ deploy_user }} group={{ deploy_user }} mode=0755
      notify: restart unicorn
      tags: deploy

    - name: delete default vhost symlink
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx
      tags: deploy

    - name: write nginx config file
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0755
      notify: restart nginx
      tags: deploy

    - name: start unicorn
      service:
        name: railsfuza
        pattern: "unicorn master"
        state: started
      tags: deploy

  handlers:
    - name: restart unicorn
      service:
        name: railsfuza
        pattern: "unicorn master"
        state: restarted
